### ISSUE TITLE
Failed to initialize the aedes broker

### ISSUE THREAD

**Issue by wbleonard** [WekanCompany/mongodb-iot-realm#2]
Greetings,

My broker is failing to start, repeatedly throwing the error:

```
Error: Failed to initialize the aedes broker
    at main (/usr/src/app/src/index.js:81:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I'm still troubleshooting, but if you have any thoughts I'm all ears :-).

**Comment by wbleonard** [comment]
I believe my problem was that I was trying to run your image. It started successfully after switching to my image.
